// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnJh3gxRXskKIo5lzQ3sF5lqPUSEeFnus',
    appId: '1:219892714381:web:d6ee35e88ba91aa2c70bc4',
    messagingSenderId: '219892714381',
    projectId: 'merchant-portal-42b46',
    authDomain: 'merchant-portal-42b46.firebaseapp.com',
    storageBucket: 'merchant-portal-42b46.appspot.com',
    measurementId: 'G-23MFFNM8D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLVcHraENVGdKg3Hv4v-oXW9YQefeBKcw',
    appId: '1:219892714381:android:4d87c94a374a5f42c70bc4',
    messagingSenderId: '219892714381',
    projectId: 'merchant-portal-42b46',
    storageBucket: 'merchant-portal-42b46.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAuIGACTr4xWPxCu-2TTNb_O815qRMt-0',
    appId: '1:219892714381:ios:157ad03d2a0b54d1c70bc4',
    messagingSenderId: '219892714381',
    projectId: 'merchant-portal-42b46',
    storageBucket: 'merchant-portal-42b46.appspot.com',
    iosClientId: '219892714381-5mnb97uris1n23h3ojgmhnpv2hrcnkn3.apps.googleusercontent.com',
    iosBundleId: 'com.alimonapps.app',
  );
}
